"""add financial_report new wb fields 2026-04

Revision ID: 292776980fc3
Revises: e5f6a7b8c9d0
Create Date: 2026-04-09 17:57:16.485556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '292776980fc3'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=255), nullable=False, comment='ID чата'),
    sa.Column('reply_sign', sa.Text(), nullable=True, comment='Подпись чата для ответа'),
    sa.Column('client_name', sa.String(length=255), nullable=True, comment='Имя покупателя'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='nmID товара'),
    sa.Column('subject_name', sa.String(length=255), nullable=True, comment='Предмет товара'),
    sa.Column('last_message_text', sa.Text(), nullable=True, comment='Текст последнего сообщения'),
    sa.Column('last_message_dt', sa.DateTime(timezone=True), nullable=True, comment='Время последнего сообщения'),
    sa.Column('is_new', sa.Boolean(), nullable=True, comment='Новый чат (непрочитанный)'),
    sa.Column('good_card', sa.JSON(), nullable=True, comment='Карточка товара (JSON)'),
    sa.Column('last_message', sa.JSON(), nullable=True, comment='Последнее сообщение (JSON)'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=True)
    op.create_index(op.f('ix_chats_last_message_dt'), 'chats', ['last_message_dt'], unique=False)
    op.create_index(op.f('ix_chats_nm_id'), 'chats', ['nm_id'], unique=False)
    op.drop_index(op.f('ix_wb_campaign_stats_advert_id'), table_name='campaign_stats')
    op.drop_index(op.f('ix_wb_campaign_stats_date'), table_name='campaign_stats')
    op.create_index(op.f('ix_campaign_stats_advert_id'), 'campaign_stats', ['advert_id'], unique=False)
    op.create_index(op.f('ix_campaign_stats_date'), 'campaign_stats', ['date'], unique=False)
    op.drop_index(op.f('ix_wb_campaigns_advert_id'), table_name='campaigns')
    op.drop_index(op.f('ix_wb_campaigns_status'), table_name='campaigns')
    op.create_index(op.f('ix_campaigns_advert_id'), 'campaigns', ['advert_id'], unique=True)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.drop_index(op.f('ix_wb_claims_claim_id'), table_name='claims')
    op.drop_index(op.f('ix_wb_claims_created_date'), table_name='claims')
    op.create_index(op.f('ix_claims_claim_id'), 'claims', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claims_created_date'), 'claims', ['created_date'], unique=False)
    op.alter_column('dbs_orders', 'order_id',
               existing_type=sa.BIGINT(),
               comment='id',
               existing_comment='id — ID заказа',
               existing_nullable=False)
    op.alter_column('dbs_orders', 'order_uid',
               existing_type=sa.VARCHAR(length=100),
               comment='orderUid',
               existing_comment='orderUid — UUID заказа',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'group_id',
               existing_type=sa.VARCHAR(length=50),
               comment='groupId',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'rid',
               existing_type=sa.VARCHAR(length=100),
               comment='rid',
               existing_comment='rid — ID позиции',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='createdAt',
               existing_comment='createdAt — дата создания',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'article',
               existing_type=sa.VARCHAR(length=100),
               comment='article',
               existing_comment='article — артикул продавца',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'color_code',
               existing_type=sa.VARCHAR(length=50),
               comment='colorCode',
               existing_comment='colorCode — код цвета',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'nm_id',
               existing_type=sa.BIGINT(),
               comment='nmId',
               existing_comment='nmId — артикул WB',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'chrt_id',
               existing_type=sa.BIGINT(),
               comment='chrtId',
               existing_comment='chrtId — ID размера',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'price',
               existing_type=sa.INTEGER(),
               comment='price',
               existing_comment='price — цена',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'converted_currency_code',
               existing_type=sa.INTEGER(),
               comment='convertedCurrencyCode',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'final_price',
               existing_type=sa.INTEGER(),
               comment='finalPrice',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'converted_final_price',
               existing_type=sa.INTEGER(),
               comment='convertedFinalPrice',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'scan_price',
               existing_type=sa.INTEGER(),
               comment='scanPrice',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'wb_sticker_id',
               existing_type=sa.BIGINT(),
               comment='wbStickerId',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'comment',
               existing_type=sa.VARCHAR(length=500),
               comment='comment',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'address',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='address',
               existing_comment='address — адрес доставки',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='options',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('dbw_orders', 'order_id',
               existing_type=sa.BIGINT(),
               comment='id',
               existing_comment='id — ID заказа',
               existing_nullable=False)
    op.alter_column('dbw_orders', 'order_uid',
               existing_type=sa.VARCHAR(length=100),
               comment='orderUid',
               existing_comment='orderUid — UUID заказа',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'group_id',
               existing_type=sa.VARCHAR(length=50),
               comment='groupId',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'rid',
               existing_type=sa.VARCHAR(length=100),
               comment='rid',
               existing_comment='rid — ID позиции',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='createdAt',
               existing_comment='createdAt — дата создания',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'article',
               existing_type=sa.VARCHAR(length=100),
               comment='article',
               existing_comment='article — артикул продавца',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'color_code',
               existing_type=sa.VARCHAR(length=50),
               comment='colorCode',
               existing_comment='colorCode — код цвета',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'nm_id',
               existing_type=sa.BIGINT(),
               comment='nmId',
               existing_comment='nmId — артикул WB',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'chrt_id',
               existing_type=sa.BIGINT(),
               comment='chrtId',
               existing_comment='chrtId — ID размера',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'price',
               existing_type=sa.INTEGER(),
               comment='price',
               existing_comment='price — цена',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'currency_code',
               existing_type=sa.INTEGER(),
               comment='currencyCode',
               existing_comment='currencyCode — ISO 4217',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'converted_currency_code',
               existing_type=sa.INTEGER(),
               comment='convertedCurrencyCode',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'comment',
               existing_type=sa.VARCHAR(length=500),
               comment='comment',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='options',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('fbs_orders', 'order_id',
               existing_type=sa.BIGINT(),
               comment='id',
               existing_comment='id — ID сборочного задания',
               existing_nullable=False)
    op.alter_column('fbs_orders', 'order_uid',
               existing_type=sa.VARCHAR(length=100),
               comment='orderUid',
               existing_comment='orderUid — UUID заказа',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'rid',
               existing_type=sa.VARCHAR(length=100),
               comment='rid',
               existing_comment='rid — уникальный ID позиции',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='createdAt',
               existing_comment='createdAt — дата создания',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'article',
               existing_type=sa.VARCHAR(length=100),
               comment='article',
               existing_comment='article — артикул продавца',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'color_code',
               existing_type=sa.VARCHAR(length=50),
               comment='colorCode',
               existing_comment='colorCode — код цвета',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'nm_id',
               existing_type=sa.BIGINT(),
               comment='nmId',
               existing_comment='nmId — артикул WB',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'chrt_id',
               existing_type=sa.BIGINT(),
               comment='chrtId',
               existing_comment='chrtId — ID размера',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'price',
               existing_type=sa.INTEGER(),
               comment='price',
               existing_comment='price — цена в копейках × 100',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'converted_price',
               existing_type=sa.INTEGER(),
               comment='convertedPrice',
               existing_comment='convertedPrice — цена в валюте продавца',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'currency_code',
               existing_type=sa.INTEGER(),
               comment='currencyCode',
               existing_comment='currencyCode — код валюты ISO 4217',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'delivery_type',
               existing_type=sa.VARCHAR(length=20),
               comment='deliveryType',
               existing_comment='deliveryType — тип доставки (fbs/dbs/...)',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'supply_id',
               existing_type=sa.VARCHAR(length=50),
               comment='supplyId',
               existing_comment='supplyId — ID поставки',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'warehouse_id',
               existing_type=sa.BIGINT(),
               comment='warehouseId',
               existing_comment='warehouseId — ID склада продавца',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'office_id',
               existing_type=sa.BIGINT(),
               comment='officeId',
               existing_comment='officeId — ID офиса WB',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'cargo_type',
               existing_type=sa.INTEGER(),
               comment='cargoType',
               existing_comment='cargoType — тип груза',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'cross_border_type',
               existing_type=sa.INTEGER(),
               comment='crossBorderType',
               existing_comment='crossBorderType — кроссбордер тип',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'scan_price',
               existing_type=sa.INTEGER(),
               comment='scanPrice',
               existing_comment='scanPrice — цена при сканировании',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'is_zero_order',
               existing_type=sa.BOOLEAN(),
               comment='isZeroOrder',
               existing_comment='isZeroOrder — нулевой заказ',
               existing_nullable=False)
    op.alter_column('fbs_orders', 'comment',
               existing_type=sa.VARCHAR(length=500),
               comment='comment',
               existing_comment='comment — комментарий',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'skus',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='skus',
               existing_comment='skus — баркоды',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'offices',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='offices',
               existing_comment='offices — офисы доставки',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'address',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='address',
               existing_comment='address — адрес доставки',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='options',
               existing_comment='options — доп. опции',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('fbs_supplies', 'supply_id',
               existing_type=sa.VARCHAR(length=50),
               comment='id',
               existing_comment='id � WB-GI-...',
               existing_nullable=False)
    op.alter_column('fbw_supplies', 'supply_id',
               existing_type=sa.BIGINT(),
               comment='supplyID',
               existing_comment='ID поставки WB (supplyID)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fbw_supplies', 'preorder_id',
               existing_type=sa.BIGINT(),
               comment='preorderID',
               existing_comment='ID заказа (preorderID)',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'status_id',
               existing_type=sa.INTEGER(),
               comment='statusID',
               existing_comment='ID статуса (1-5)',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'box_type_id',
               existing_type=sa.INTEGER(),
               comment='boxTypeID',
               existing_comment='ID типа поставки (0-5)',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'is_box_on_pallet',
               existing_type=sa.BOOLEAN(),
               comment='isBoxOnPallet',
               existing_comment='Поштучная паллета',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'create_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='createDate',
               existing_comment='Дата создания',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'supply_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='supplyDate',
               existing_comment='Плановая дата отгрузки',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'fact_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='factDate',
               existing_comment='Дата фактической отгрузки',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'updated_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='updatedDate',
               existing_comment='Дата последнего изменения',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'phone',
               existing_type=sa.VARCHAR(length=50),
               comment='phone',
               existing_comment='Телефон',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Исходные данные WB (JSON)',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата синхронизации',
               existing_nullable=False)
    op.add_column('fbw_supply_goods', sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='nmID'))
    op.add_column('fbw_supply_goods', sa.Column('need_kiz', sa.Boolean(), nullable=True, comment='needKiz'))
    op.add_column('fbw_supply_goods', sa.Column('tnved', sa.String(length=20), nullable=True, comment='tnved'))
    op.add_column('fbw_supply_goods', sa.Column('tech_size', sa.String(length=50), nullable=True, comment='techSize'))
    op.add_column('fbw_supply_goods', sa.Column('color', sa.String(length=100), nullable=True, comment='color'))
    op.add_column('fbw_supply_goods', sa.Column('supplier_box_amount', sa.Integer(), nullable=True, comment='supplierBoxAmount'))
    op.add_column('fbw_supply_goods', sa.Column('ready_for_sale_quantity', sa.Integer(), nullable=True, comment='readyForSaleQuantity'))
    op.add_column('fbw_supply_goods', sa.Column('accepted_quantity', sa.Integer(), nullable=True, comment='acceptedQuantity'))
    op.add_column('fbw_supply_goods', sa.Column('unloading_quantity', sa.Integer(), nullable=True, comment='unloadingQuantity'))
    op.alter_column('fbw_supply_goods', 'supply_id',
               existing_type=sa.BIGINT(),
               comment='supplyID',
               existing_comment='ID поставки FBW',
               existing_nullable=False)
    op.alter_column('fbw_supply_goods', 'barcode',
               existing_type=sa.VARCHAR(length=50),
               comment='barcode',
               existing_comment='Баркод товара',
               existing_nullable=True)
    op.alter_column('fbw_supply_goods', 'vendor_code',
               existing_type=sa.VARCHAR(length=100),
               comment='vendorCode',
               existing_comment='Артикул продавца',
               existing_nullable=True)
    op.alter_column('fbw_supply_goods', 'quantity',
               existing_type=sa.INTEGER(),
               comment='quantity',
               existing_comment='Количество в поставке',
               existing_nullable=True)
    op.alter_column('fbw_supply_goods', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Исходные данные WB (JSON)',
               existing_nullable=True)
    op.alter_column('fbw_supply_goods', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата синхронизации',
               existing_nullable=False)
    op.drop_column('fbw_supply_goods', 'brand')
    op.drop_column('fbw_supply_goods', 'name')
    op.drop_column('fbw_supply_goods', 'subject')
    op.alter_column('fbw_transit_tariffs', 'transit_warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               comment='transitWarehouseName',
               existing_comment='Транзитный склад',
               existing_nullable=False)
    op.alter_column('fbw_transit_tariffs', 'destination_warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               comment='destinationWarehouseName',
               existing_comment='Склад назначения',
               existing_nullable=False)
    op.alter_column('fbw_transit_tariffs', 'active_from',
               existing_type=sa.VARCHAR(length=50),
               comment='activeFrom',
               existing_comment='Дата начала действия (ISO 8601)',
               existing_nullable=True)
    op.alter_column('fbw_transit_tariffs', 'box_tariff',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='boxTariff',
               existing_comment='Тарифы за транзит коробов (JSON)',
               existing_nullable=True)
    op.alter_column('fbw_transit_tariffs', 'pallet_tariff',
               existing_type=sa.INTEGER(),
               comment='palletTariff',
               existing_comment='Тариф за паллету, руб.',
               existing_nullable=True)
    op.alter_column('fbw_transit_tariffs', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Исходные данные WB (JSON)',
               existing_nullable=True)
    op.alter_column('fbw_transit_tariffs', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('fbw_warehouses', 'id',
               existing_type=sa.BIGINT(),
               comment='ID',
               existing_comment='ID склада WB',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fbw_warehouses', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='name',
               existing_comment='Название склада',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment='address',
               existing_comment='Адрес склада',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'work_time',
               existing_type=sa.VARCHAR(length=100),
               comment='workTime',
               existing_comment='Режим работы',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='isActive',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'is_transit_active',
               existing_type=sa.BOOLEAN(),
               comment='isTransitActive',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Исходные данные WB (JSON)',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата синхронизации',
               existing_nullable=False)
    op.drop_index(op.f('ix_wb_feedbacks_created_date'), table_name='feedbacks')
    op.drop_index(op.f('ix_wb_feedbacks_feedback_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_wb_feedbacks_nm_id'), table_name='feedbacks')
    op.create_index(op.f('ix_feedbacks_created_date'), 'feedbacks', ['created_date'], unique=False)
    op.create_index(op.f('ix_feedbacks_feedback_id'), 'feedbacks', ['feedback_id'], unique=True)
    op.create_index(op.f('ix_feedbacks_nm_id'), 'feedbacks', ['nm_id'], unique=False)
    op.add_column('financial_report', sa.Column('article_substitution', sa.BigInteger(), nullable=True, comment='ID подменного артикула (WB 2026-04)'))
    op.add_column('financial_report', sa.Column('sale_price_affiliated_discount_prc', sa.Numeric(precision=8, scale=2), nullable=True, comment='Скидка по подменному артикулу, % (WB 2026-04)'))
    op.add_column('financial_report', sa.Column('sale_price_wholesale_discount_prc', sa.Numeric(precision=8, scale=2), nullable=True, comment='Оптовая скидка для бизнеса, % (WB 2026-04)'))
    op.drop_index(op.f('ix_wb_financial_report_barcode'), table_name='financial_report')
    op.drop_index(op.f('ix_wb_financial_report_nm_id'), table_name='financial_report')
    op.drop_index(op.f('ix_wb_financial_report_order_dt'), table_name='financial_report')
    op.drop_index(op.f('ix_wb_financial_report_realizationreport_id'), table_name='financial_report')
    op.drop_index(op.f('ix_wb_financial_report_rrd_id'), table_name='financial_report')
    op.drop_index(op.f('ix_wb_financial_report_sale_dt'), table_name='financial_report')
    op.drop_index(op.f('ix_wb_financial_report_srid'), table_name='financial_report')
    op.create_index(op.f('ix_financial_report_barcode'), 'financial_report', ['barcode'], unique=False)
    op.create_index(op.f('ix_financial_report_nm_id'), 'financial_report', ['nm_id'], unique=False)
    op.create_index(op.f('ix_financial_report_order_dt'), 'financial_report', ['order_dt'], unique=False)
    op.create_index(op.f('ix_financial_report_realizationreport_id'), 'financial_report', ['realizationreport_id'], unique=False)
    op.create_index(op.f('ix_financial_report_rrd_id'), 'financial_report', ['rrd_id'], unique=True)
    op.create_index(op.f('ix_financial_report_sale_dt'), 'financial_report', ['sale_dt'], unique=False)
    op.create_index(op.f('ix_financial_report_srid'), 'financial_report', ['srid'], unique=False)
    op.drop_index(op.f('ix_wb_orders_report_barcode'), table_name='orders_report')
    op.drop_index(op.f('ix_wb_orders_report_date'), table_name='orders_report')
    op.drop_index(op.f('ix_wb_orders_report_nm_id'), table_name='orders_report')
    op.drop_index(op.f('ix_wb_orders_report_odid'), table_name='orders_report')
    op.create_index(op.f('ix_orders_report_barcode'), 'orders_report', ['barcode'], unique=False)
    op.create_index(op.f('ix_orders_report_date'), 'orders_report', ['date'], unique=False)
    op.create_index(op.f('ix_orders_report_nm_id'), 'orders_report', ['nm_id'], unique=False)
    op.create_index(op.f('ix_orders_report_odid'), 'orders_report', ['odid'], unique=True)
    op.alter_column('pickup_orders', 'order_id',
               existing_type=sa.BIGINT(),
               comment='id',
               existing_comment='id — ID заказа',
               existing_nullable=False)
    op.alter_column('pickup_orders', 'rid',
               existing_type=sa.VARCHAR(length=100),
               comment='rid',
               existing_comment='rid — ID позиции',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='createdAt',
               existing_comment='createdAt — дата создания',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'article',
               existing_type=sa.VARCHAR(length=100),
               comment='article',
               existing_comment='article — артикул продавца',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'nm_id',
               existing_type=sa.BIGINT(),
               comment='nmId',
               existing_comment='nmId — артикул WB',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'chrt_id',
               existing_type=sa.BIGINT(),
               comment='chrtId',
               existing_comment='chrtId — ID размера',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'price',
               existing_type=sa.INTEGER(),
               comment='price',
               existing_comment='price — цена',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'converted_price',
               existing_type=sa.INTEGER(),
               comment='convertedPrice',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'currency_code',
               existing_type=sa.INTEGER(),
               comment='currencyCode',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'converted_currency_code',
               existing_type=sa.INTEGER(),
               comment='convertedCurrencyCode',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'final_price',
               existing_type=sa.INTEGER(),
               comment='finalPrice',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'converted_final_price',
               existing_type=sa.INTEGER(),
               comment='convertedFinalPrice',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'cargo_type',
               existing_type=sa.INTEGER(),
               comment='cargoType',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'order_code',
               existing_type=sa.VARCHAR(length=50),
               comment='orderCode',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'pay_mode',
               existing_type=sa.VARCHAR(length=50),
               comment='payMode',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'warehouse_address',
               existing_type=sa.VARCHAR(length=500),
               comment='warehouseAddress',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата синхронизации',
               existing_nullable=False)
    op.drop_index(op.f('ix_wb_promotions_promotion_id'), table_name='promotions')
    op.create_index(op.f('ix_promotions_promotion_id'), 'promotions', ['promotion_id'], unique=True)
    op.drop_index(op.f('ix_wb_questions_created_date'), table_name='questions')
    op.drop_index(op.f('ix_wb_questions_nm_id'), table_name='questions')
    op.drop_index(op.f('ix_wb_questions_question_id'), table_name='questions')
    op.create_index(op.f('ix_questions_created_date'), 'questions', ['created_date'], unique=False)
    op.create_index(op.f('ix_questions_nm_id'), 'questions', ['nm_id'], unique=False)
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=True)
    op.drop_index(op.f('ix_wb_sales_report_barcode'), table_name='sales_report')
    op.drop_index(op.f('ix_wb_sales_report_date'), table_name='sales_report')
    op.drop_index(op.f('ix_wb_sales_report_nm_id'), table_name='sales_report')
    op.drop_index(op.f('ix_wb_sales_report_odid'), table_name='sales_report')
    op.drop_index(op.f('ix_wb_sales_report_sale_id'), table_name='sales_report')
    op.drop_index(op.f('ix_wb_sales_report_srid'), table_name='sales_report')
    op.create_index(op.f('ix_sales_report_barcode'), 'sales_report', ['barcode'], unique=False)
    op.create_index(op.f('ix_sales_report_date'), 'sales_report', ['date'], unique=False)
    op.create_index(op.f('ix_sales_report_nm_id'), 'sales_report', ['nm_id'], unique=False)
    op.create_index(op.f('ix_sales_report_odid'), 'sales_report', ['odid'], unique=False)
    op.create_index(op.f('ix_sales_report_sale_id'), 'sales_report', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sales_report_srid'), 'sales_report', ['srid'], unique=True)
    op.drop_index(op.f('ix_wb_stocks_barcode'), table_name='stocks')
    op.drop_index(op.f('ix_wb_stocks_last_change_date'), table_name='stocks')
    op.drop_index(op.f('ix_wb_stocks_nm_id'), table_name='stocks')
    op.drop_index(op.f('ix_wb_stocks_warehouse_name'), table_name='stocks')
    op.create_index(op.f('ix_stocks_barcode'), 'stocks', ['barcode'], unique=False)
    op.create_index(op.f('ix_stocks_last_change_date'), 'stocks', ['last_change_date'], unique=False)
    op.create_index(op.f('ix_stocks_nm_id'), 'stocks', ['nm_id'], unique=False)
    op.create_index(op.f('ix_stocks_warehouse_name'), 'stocks', ['warehouse_name'], unique=False)
    op.drop_index(op.f('ix_wb_tariffs_box_warehouse_name'), table_name='tariffs_box')
    op.create_index(op.f('ix_tariffs_box_warehouse_name'), 'tariffs_box', ['warehouse_name'], unique=True)
    op.drop_index(op.f('ix_wb_tariffs_commission_subject_id'), table_name='tariffs_commission')
    op.create_index(op.f('ix_tariffs_commission_subject_id'), 'tariffs_commission', ['subject_id'], unique=True)
    op.drop_index(op.f('ix_wb_tariffs_pallet_warehouse_name'), table_name='tariffs_pallet')
    op.create_index(op.f('ix_tariffs_pallet_warehouse_name'), 'tariffs_pallet', ['warehouse_name'], unique=True)
    op.alter_column('tariffs_supply', 'warehouse_id',
               existing_type=sa.BIGINT(),
               comment='warehouseID',
               existing_comment='ID склада WB',
               existing_nullable=False)
    op.alter_column('tariffs_supply', 'warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               comment='warehouseName',
               existing_comment='Название склада',
               existing_nullable=True)
    op.alter_column('tariffs_supply', 'date',
               existing_type=sa.VARCHAR(length=50),
               comment='date',
               existing_comment='Дата начала действия',
               existing_nullable=True)
    op.alter_column('tariffs_supply', 'coefficient',
               existing_type=sa.INTEGER(),
               comment='coefficient',
               existing_comment='Коэффициент: 0=бесплатно, -1=закрыт',
               existing_nullable=True)
    op.alter_column('tariffs_supply', 'allow_unload',
               existing_type=sa.BOOLEAN(),
               comment='allowUnload',
               existing_comment='Доступность приёмки',
               existing_nullable=True)
    op.alter_column('tariffs_supply', 'box_type_id',
               existing_type=sa.INTEGER(),
               comment='boxTypeID',
               existing_comment='Тип поставки: 2=Короба, 5=Паллеты, 6=Суперсейф',
               existing_nullable=True)
    op.drop_index(op.f('ix_wb_tariffs_supply_warehouse_id'), table_name='tariffs_supply')
    op.create_index(op.f('ix_tariffs_supply_warehouse_id'), 'tariffs_supply', ['warehouse_id'], unique=False)
    op.drop_table_comment(
        'tariffs_supply',
        existing_comment='Коэффициенты приёмки на складах WB',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'tariffs_supply',
        'Коэффициенты приёмки на складах WB',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_tariffs_supply_warehouse_id'), table_name='tariffs_supply')
    op.create_index(op.f('ix_wb_tariffs_supply_warehouse_id'), 'tariffs_supply', ['warehouse_id'], unique=False)
    op.alter_column('tariffs_supply', 'box_type_id',
               existing_type=sa.INTEGER(),
               comment='Тип поставки: 2=Короба, 5=Паллеты, 6=Суперсейф',
               existing_comment='boxTypeID',
               existing_nullable=True)
    op.alter_column('tariffs_supply', 'allow_unload',
               existing_type=sa.BOOLEAN(),
               comment='Доступность приёмки',
               existing_comment='allowUnload',
               existing_nullable=True)
    op.alter_column('tariffs_supply', 'coefficient',
               existing_type=sa.INTEGER(),
               comment='Коэффициент: 0=бесплатно, -1=закрыт',
               existing_comment='coefficient',
               existing_nullable=True)
    op.alter_column('tariffs_supply', 'date',
               existing_type=sa.VARCHAR(length=50),
               comment='Дата начала действия',
               existing_comment='date',
               existing_nullable=True)
    op.alter_column('tariffs_supply', 'warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Название склада',
               existing_comment='warehouseName',
               existing_nullable=True)
    op.alter_column('tariffs_supply', 'warehouse_id',
               existing_type=sa.BIGINT(),
               comment='ID склада WB',
               existing_comment='warehouseID',
               existing_nullable=False)
    op.drop_index(op.f('ix_tariffs_pallet_warehouse_name'), table_name='tariffs_pallet')
    op.create_index(op.f('ix_wb_tariffs_pallet_warehouse_name'), 'tariffs_pallet', ['warehouse_name'], unique=True)
    op.drop_index(op.f('ix_tariffs_commission_subject_id'), table_name='tariffs_commission')
    op.create_index(op.f('ix_wb_tariffs_commission_subject_id'), 'tariffs_commission', ['subject_id'], unique=True)
    op.drop_index(op.f('ix_tariffs_box_warehouse_name'), table_name='tariffs_box')
    op.create_index(op.f('ix_wb_tariffs_box_warehouse_name'), 'tariffs_box', ['warehouse_name'], unique=True)
    op.drop_index(op.f('ix_stocks_warehouse_name'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_nm_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_last_change_date'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_barcode'), table_name='stocks')
    op.create_index(op.f('ix_wb_stocks_warehouse_name'), 'stocks', ['warehouse_name'], unique=False)
    op.create_index(op.f('ix_wb_stocks_nm_id'), 'stocks', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_stocks_last_change_date'), 'stocks', ['last_change_date'], unique=False)
    op.create_index(op.f('ix_wb_stocks_barcode'), 'stocks', ['barcode'], unique=False)
    op.drop_index(op.f('ix_sales_report_srid'), table_name='sales_report')
    op.drop_index(op.f('ix_sales_report_sale_id'), table_name='sales_report')
    op.drop_index(op.f('ix_sales_report_odid'), table_name='sales_report')
    op.drop_index(op.f('ix_sales_report_nm_id'), table_name='sales_report')
    op.drop_index(op.f('ix_sales_report_date'), table_name='sales_report')
    op.drop_index(op.f('ix_sales_report_barcode'), table_name='sales_report')
    op.create_index(op.f('ix_wb_sales_report_srid'), 'sales_report', ['srid'], unique=True)
    op.create_index(op.f('ix_wb_sales_report_sale_id'), 'sales_report', ['sale_id'], unique=False)
    op.create_index(op.f('ix_wb_sales_report_odid'), 'sales_report', ['odid'], unique=False)
    op.create_index(op.f('ix_wb_sales_report_nm_id'), 'sales_report', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_sales_report_date'), 'sales_report', ['date'], unique=False)
    op.create_index(op.f('ix_wb_sales_report_barcode'), 'sales_report', ['barcode'], unique=False)
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_nm_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_date'), table_name='questions')
    op.create_index(op.f('ix_wb_questions_question_id'), 'questions', ['question_id'], unique=True)
    op.create_index(op.f('ix_wb_questions_nm_id'), 'questions', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_questions_created_date'), 'questions', ['created_date'], unique=False)
    op.drop_index(op.f('ix_promotions_promotion_id'), table_name='promotions')
    op.create_index(op.f('ix_wb_promotions_promotion_id'), 'promotions', ['promotion_id'], unique=True)
    op.alter_column('pickup_orders', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('pickup_orders', 'warehouse_address',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='warehouseAddress',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'pay_mode',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='payMode',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'order_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='orderCode',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'cargo_type',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='cargoType',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'converted_final_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='convertedFinalPrice',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'final_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='finalPrice',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'converted_currency_code',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='convertedCurrencyCode',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'currency_code',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='currencyCode',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'converted_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='convertedPrice',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'price',
               existing_type=sa.INTEGER(),
               comment='price — цена',
               existing_comment='price',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'chrt_id',
               existing_type=sa.BIGINT(),
               comment='chrtId — ID размера',
               existing_comment='chrtId',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'nm_id',
               existing_type=sa.BIGINT(),
               comment='nmId — артикул WB',
               existing_comment='nmId',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'article',
               existing_type=sa.VARCHAR(length=100),
               comment='article — артикул продавца',
               existing_comment='article',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='createdAt — дата создания',
               existing_comment='createdAt',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'rid',
               existing_type=sa.VARCHAR(length=100),
               comment='rid — ID позиции',
               existing_comment='rid',
               existing_nullable=True)
    op.alter_column('pickup_orders', 'order_id',
               existing_type=sa.BIGINT(),
               comment='id — ID заказа',
               existing_comment='id',
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_report_odid'), table_name='orders_report')
    op.drop_index(op.f('ix_orders_report_nm_id'), table_name='orders_report')
    op.drop_index(op.f('ix_orders_report_date'), table_name='orders_report')
    op.drop_index(op.f('ix_orders_report_barcode'), table_name='orders_report')
    op.create_index(op.f('ix_wb_orders_report_odid'), 'orders_report', ['odid'], unique=True)
    op.create_index(op.f('ix_wb_orders_report_nm_id'), 'orders_report', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_orders_report_date'), 'orders_report', ['date'], unique=False)
    op.create_index(op.f('ix_wb_orders_report_barcode'), 'orders_report', ['barcode'], unique=False)
    op.drop_index(op.f('ix_financial_report_srid'), table_name='financial_report')
    op.drop_index(op.f('ix_financial_report_sale_dt'), table_name='financial_report')
    op.drop_index(op.f('ix_financial_report_rrd_id'), table_name='financial_report')
    op.drop_index(op.f('ix_financial_report_realizationreport_id'), table_name='financial_report')
    op.drop_index(op.f('ix_financial_report_order_dt'), table_name='financial_report')
    op.drop_index(op.f('ix_financial_report_nm_id'), table_name='financial_report')
    op.drop_index(op.f('ix_financial_report_barcode'), table_name='financial_report')
    op.create_index(op.f('ix_wb_financial_report_srid'), 'financial_report', ['srid'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_sale_dt'), 'financial_report', ['sale_dt'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_rrd_id'), 'financial_report', ['rrd_id'], unique=True)
    op.create_index(op.f('ix_wb_financial_report_realizationreport_id'), 'financial_report', ['realizationreport_id'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_order_dt'), 'financial_report', ['order_dt'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_nm_id'), 'financial_report', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_barcode'), 'financial_report', ['barcode'], unique=False)
    op.drop_column('financial_report', 'sale_price_wholesale_discount_prc')
    op.drop_column('financial_report', 'sale_price_affiliated_discount_prc')
    op.drop_column('financial_report', 'article_substitution')
    op.drop_index(op.f('ix_feedbacks_nm_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_feedback_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_created_date'), table_name='feedbacks')
    op.create_index(op.f('ix_wb_feedbacks_nm_id'), 'feedbacks', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_feedbacks_feedback_id'), 'feedbacks', ['feedback_id'], unique=True)
    op.create_index(op.f('ix_wb_feedbacks_created_date'), 'feedbacks', ['created_date'], unique=False)
    op.alter_column('fbw_warehouses', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('fbw_warehouses', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Исходные данные WB (JSON)',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'is_transit_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='isTransitActive',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='isActive',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'work_time',
               existing_type=sa.VARCHAR(length=100),
               comment='Режим работы',
               existing_comment='workTime',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'address',
               existing_type=sa.VARCHAR(length=500),
               comment='Адрес склада',
               existing_comment='address',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Название склада',
               existing_comment='name',
               existing_nullable=True)
    op.alter_column('fbw_warehouses', 'id',
               existing_type=sa.BIGINT(),
               comment='ID склада WB',
               existing_comment='ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fbw_transit_tariffs', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('fbw_transit_tariffs', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Исходные данные WB (JSON)',
               existing_nullable=True)
    op.alter_column('fbw_transit_tariffs', 'pallet_tariff',
               existing_type=sa.INTEGER(),
               comment='Тариф за паллету, руб.',
               existing_comment='palletTariff',
               existing_nullable=True)
    op.alter_column('fbw_transit_tariffs', 'box_tariff',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Тарифы за транзит коробов (JSON)',
               existing_comment='boxTariff',
               existing_nullable=True)
    op.alter_column('fbw_transit_tariffs', 'active_from',
               existing_type=sa.VARCHAR(length=50),
               comment='Дата начала действия (ISO 8601)',
               existing_comment='activeFrom',
               existing_nullable=True)
    op.alter_column('fbw_transit_tariffs', 'destination_warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Склад назначения',
               existing_comment='destinationWarehouseName',
               existing_nullable=False)
    op.alter_column('fbw_transit_tariffs', 'transit_warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Транзитный склад',
               existing_comment='transitWarehouseName',
               existing_nullable=False)
    op.add_column('fbw_supply_goods', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Предмет товара'))
    op.add_column('fbw_supply_goods', sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Наименование товара'))
    op.add_column('fbw_supply_goods', sa.Column('brand', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Бренд товара'))
    op.alter_column('fbw_supply_goods', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('fbw_supply_goods', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Исходные данные WB (JSON)',
               existing_nullable=True)
    op.alter_column('fbw_supply_goods', 'quantity',
               existing_type=sa.INTEGER(),
               comment='Количество в поставке',
               existing_comment='quantity',
               existing_nullable=True)
    op.alter_column('fbw_supply_goods', 'vendor_code',
               existing_type=sa.VARCHAR(length=100),
               comment='Артикул продавца',
               existing_comment='vendorCode',
               existing_nullable=True)
    op.alter_column('fbw_supply_goods', 'barcode',
               existing_type=sa.VARCHAR(length=50),
               comment='Баркод товара',
               existing_comment='barcode',
               existing_nullable=True)
    op.alter_column('fbw_supply_goods', 'supply_id',
               existing_type=sa.BIGINT(),
               comment='ID поставки FBW',
               existing_comment='supplyID',
               existing_nullable=False)
    op.drop_column('fbw_supply_goods', 'unloading_quantity')
    op.drop_column('fbw_supply_goods', 'accepted_quantity')
    op.drop_column('fbw_supply_goods', 'ready_for_sale_quantity')
    op.drop_column('fbw_supply_goods', 'supplier_box_amount')
    op.drop_column('fbw_supply_goods', 'color')
    op.drop_column('fbw_supply_goods', 'tech_size')
    op.drop_column('fbw_supply_goods', 'tnved')
    op.drop_column('fbw_supply_goods', 'need_kiz')
    op.drop_column('fbw_supply_goods', 'nm_id')
    op.alter_column('fbw_supplies', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('fbw_supplies', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Исходные данные WB (JSON)',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'phone',
               existing_type=sa.VARCHAR(length=50),
               comment='Телефон',
               existing_comment='phone',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'updated_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата последнего изменения',
               existing_comment='updatedDate',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'fact_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата фактической отгрузки',
               existing_comment='factDate',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'supply_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Плановая дата отгрузки',
               existing_comment='supplyDate',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'create_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата создания',
               existing_comment='createDate',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'is_box_on_pallet',
               existing_type=sa.BOOLEAN(),
               comment='Поштучная паллета',
               existing_comment='isBoxOnPallet',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'box_type_id',
               existing_type=sa.INTEGER(),
               comment='ID типа поставки (0-5)',
               existing_comment='boxTypeID',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'status_id',
               existing_type=sa.INTEGER(),
               comment='ID статуса (1-5)',
               existing_comment='statusID',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'preorder_id',
               existing_type=sa.BIGINT(),
               comment='ID заказа (preorderID)',
               existing_comment='preorderID',
               existing_nullable=True)
    op.alter_column('fbw_supplies', 'supply_id',
               existing_type=sa.BIGINT(),
               comment='ID поставки WB (supplyID)',
               existing_comment='supplyID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fbs_supplies', 'supply_id',
               existing_type=sa.VARCHAR(length=50),
               comment='id � WB-GI-...',
               existing_comment='id',
               existing_nullable=False)
    op.alter_column('fbs_orders', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('fbs_orders', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='options — доп. опции',
               existing_comment='options',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'address',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='address — адрес доставки',
               existing_comment='address',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'offices',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='offices — офисы доставки',
               existing_comment='offices',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'skus',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='skus — баркоды',
               existing_comment='skus',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'comment',
               existing_type=sa.VARCHAR(length=500),
               comment='comment — комментарий',
               existing_comment='comment',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'is_zero_order',
               existing_type=sa.BOOLEAN(),
               comment='isZeroOrder — нулевой заказ',
               existing_comment='isZeroOrder',
               existing_nullable=False)
    op.alter_column('fbs_orders', 'scan_price',
               existing_type=sa.INTEGER(),
               comment='scanPrice — цена при сканировании',
               existing_comment='scanPrice',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'cross_border_type',
               existing_type=sa.INTEGER(),
               comment='crossBorderType — кроссбордер тип',
               existing_comment='crossBorderType',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'cargo_type',
               existing_type=sa.INTEGER(),
               comment='cargoType — тип груза',
               existing_comment='cargoType',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'office_id',
               existing_type=sa.BIGINT(),
               comment='officeId — ID офиса WB',
               existing_comment='officeId',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'warehouse_id',
               existing_type=sa.BIGINT(),
               comment='warehouseId — ID склада продавца',
               existing_comment='warehouseId',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'supply_id',
               existing_type=sa.VARCHAR(length=50),
               comment='supplyId — ID поставки',
               existing_comment='supplyId',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'delivery_type',
               existing_type=sa.VARCHAR(length=20),
               comment='deliveryType — тип доставки (fbs/dbs/...)',
               existing_comment='deliveryType',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'currency_code',
               existing_type=sa.INTEGER(),
               comment='currencyCode — код валюты ISO 4217',
               existing_comment='currencyCode',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'converted_price',
               existing_type=sa.INTEGER(),
               comment='convertedPrice — цена в валюте продавца',
               existing_comment='convertedPrice',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'price',
               existing_type=sa.INTEGER(),
               comment='price — цена в копейках × 100',
               existing_comment='price',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'chrt_id',
               existing_type=sa.BIGINT(),
               comment='chrtId — ID размера',
               existing_comment='chrtId',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'nm_id',
               existing_type=sa.BIGINT(),
               comment='nmId — артикул WB',
               existing_comment='nmId',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'color_code',
               existing_type=sa.VARCHAR(length=50),
               comment='colorCode — код цвета',
               existing_comment='colorCode',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'article',
               existing_type=sa.VARCHAR(length=100),
               comment='article — артикул продавца',
               existing_comment='article',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='createdAt — дата создания',
               existing_comment='createdAt',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'rid',
               existing_type=sa.VARCHAR(length=100),
               comment='rid — уникальный ID позиции',
               existing_comment='rid',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'order_uid',
               existing_type=sa.VARCHAR(length=100),
               comment='orderUid — UUID заказа',
               existing_comment='orderUid',
               existing_nullable=True)
    op.alter_column('fbs_orders', 'order_id',
               existing_type=sa.BIGINT(),
               comment='id — ID сборочного задания',
               existing_comment='id',
               existing_nullable=False)
    op.alter_column('dbw_orders', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('dbw_orders', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='options',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'comment',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='comment',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'converted_currency_code',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='convertedCurrencyCode',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'currency_code',
               existing_type=sa.INTEGER(),
               comment='currencyCode — ISO 4217',
               existing_comment='currencyCode',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'price',
               existing_type=sa.INTEGER(),
               comment='price — цена',
               existing_comment='price',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'chrt_id',
               existing_type=sa.BIGINT(),
               comment='chrtId — ID размера',
               existing_comment='chrtId',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'nm_id',
               existing_type=sa.BIGINT(),
               comment='nmId — артикул WB',
               existing_comment='nmId',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'color_code',
               existing_type=sa.VARCHAR(length=50),
               comment='colorCode — код цвета',
               existing_comment='colorCode',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'article',
               existing_type=sa.VARCHAR(length=100),
               comment='article — артикул продавца',
               existing_comment='article',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='createdAt — дата создания',
               existing_comment='createdAt',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'rid',
               existing_type=sa.VARCHAR(length=100),
               comment='rid — ID позиции',
               existing_comment='rid',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'group_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='groupId',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'order_uid',
               existing_type=sa.VARCHAR(length=100),
               comment='orderUid — UUID заказа',
               existing_comment='orderUid',
               existing_nullable=True)
    op.alter_column('dbw_orders', 'order_id',
               existing_type=sa.BIGINT(),
               comment='id — ID заказа',
               existing_comment='id',
               existing_nullable=False)
    op.alter_column('dbs_orders', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата синхронизации',
               existing_nullable=False)
    op.alter_column('dbs_orders', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='options',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'address',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='address — адрес доставки',
               existing_comment='address',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'comment',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='comment',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'wb_sticker_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='wbStickerId',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'scan_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='scanPrice',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'converted_final_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='convertedFinalPrice',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'final_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='finalPrice',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'converted_currency_code',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='convertedCurrencyCode',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'price',
               existing_type=sa.INTEGER(),
               comment='price — цена',
               existing_comment='price',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'chrt_id',
               existing_type=sa.BIGINT(),
               comment='chrtId — ID размера',
               existing_comment='chrtId',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'nm_id',
               existing_type=sa.BIGINT(),
               comment='nmId — артикул WB',
               existing_comment='nmId',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'color_code',
               existing_type=sa.VARCHAR(length=50),
               comment='colorCode — код цвета',
               existing_comment='colorCode',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'article',
               existing_type=sa.VARCHAR(length=100),
               comment='article — артикул продавца',
               existing_comment='article',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='createdAt — дата создания',
               existing_comment='createdAt',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'rid',
               existing_type=sa.VARCHAR(length=100),
               comment='rid — ID позиции',
               existing_comment='rid',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'group_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='groupId',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'order_uid',
               existing_type=sa.VARCHAR(length=100),
               comment='orderUid — UUID заказа',
               existing_comment='orderUid',
               existing_nullable=True)
    op.alter_column('dbs_orders', 'order_id',
               existing_type=sa.BIGINT(),
               comment='id — ID заказа',
               existing_comment='id',
               existing_nullable=False)
    op.drop_index(op.f('ix_claims_created_date'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_id'), table_name='claims')
    op.create_index(op.f('ix_wb_claims_created_date'), 'claims', ['created_date'], unique=False)
    op.create_index(op.f('ix_wb_claims_claim_id'), 'claims', ['claim_id'], unique=True)
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_advert_id'), table_name='campaigns')
    op.create_index(op.f('ix_wb_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_wb_campaigns_advert_id'), 'campaigns', ['advert_id'], unique=True)
    op.drop_index(op.f('ix_campaign_stats_date'), table_name='campaign_stats')
    op.drop_index(op.f('ix_campaign_stats_advert_id'), table_name='campaign_stats')
    op.create_index(op.f('ix_wb_campaign_stats_date'), 'campaign_stats', ['date'], unique=False)
    op.create_index(op.f('ix_wb_campaign_stats_advert_id'), 'campaign_stats', ['advert_id'], unique=False)
    op.drop_index(op.f('ix_chats_nm_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_last_message_dt'), table_name='chats')
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
