"""add_wb_seller_rating_and_subscriptions

Revision ID: 3c46e0d6f501
Revises: a1b2c3d4e5f6
Create Date: 2026-04-03 13:05:55.366312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3c46e0d6f501'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_prices_nm_id'), table_name='wb_prices')
    op.create_index(op.f('ix_wb_prices_nm_id'), 'wb_prices', ['nm_id'], unique=True)
    op.alter_column('wb_seller_rating', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('wb_seller_subscriptions', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('wb_tariffs_box', 'warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Название склада')
    op.alter_column('wb_tariffs_box', 'box_delivery_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Логистика, первый литр, руб.',
               existing_comment='Базовый тариф доставки, руб.',
               existing_nullable=True)
    op.alter_column('wb_tariffs_box', 'box_delivery_liter',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Логистика, дополнительный литр, руб.',
               existing_comment='Тариф доставки за литр, руб.',
               existing_nullable=True)
    op.alter_column('wb_tariffs_box', 'box_storage_base',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Хранение в день, первый литр, руб.',
               existing_comment='Базовый тариф хранения, руб./день',
               existing_nullable=True)
    op.alter_column('wb_tariffs_box', 'box_storage_liter',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Хранение в день, дополнительный литр, руб.',
               existing_comment='Тариф хранения за литр, руб./день',
               existing_nullable=True)
    op.drop_index(op.f('ix_wb_tariffs_box_warehouse_id'), table_name='wb_tariffs_box')
    op.drop_constraint(op.f('uq_tariffs_box_warehouse_name'), 'wb_tariffs_box', type_='unique')
    op.create_index(op.f('ix_wb_tariffs_box_warehouse_name'), 'wb_tariffs_box', ['warehouse_name'], unique=True)
    op.drop_column('wb_tariffs_box', 'warehouse_id')
    op.drop_column('wb_tariffs_box', 'box_storage_additional_liter')
    op.drop_column('wb_tariffs_box', 'box_delivery_additional_liter')
    op.drop_column('wb_tariffs_box', 'dt_next_box')
    op.drop_constraint(op.f('uq_tariffs_commission_subject_id'), 'wb_tariffs_commission', type_='unique')
    op.drop_index(op.f('ix_wb_tariffs_commission_subject_id'), table_name='wb_tariffs_commission')
    op.create_index(op.f('ix_wb_tariffs_commission_subject_id'), 'wb_tariffs_commission', ['subject_id'], unique=True)
    op.alter_column('wb_tariffs_pallet', 'warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Название склада')
    op.drop_index(op.f('ix_wb_tariffs_pallet_warehouse_id'), table_name='wb_tariffs_pallet')
    op.drop_constraint(op.f('uq_tariffs_pallet_warehouse_name'), 'wb_tariffs_pallet', type_='unique')
    op.create_index(op.f('ix_wb_tariffs_pallet_warehouse_name'), 'wb_tariffs_pallet', ['warehouse_name'], unique=True)
    op.drop_column('wb_tariffs_pallet', 'warehouse_id')
    op.alter_column('wb_tariffs_supply', 'date',
               existing_type=sa.VARCHAR(length=50),
               comment='Дата начала действия',
               existing_nullable=True)
    op.alter_column('wb_tariffs_supply', 'allow_unload',
               existing_type=sa.BOOLEAN(),
               comment='Доступность приёмки',
               existing_nullable=True)
    op.alter_column('wb_tariffs_supply', 'box_type_id',
               existing_type=sa.INTEGER(),
               comment='Тип поставки: 2=Короба, 5=Паллеты, 6=Суперсейф',
               existing_nullable=True)
    op.create_table_comment(
        'wb_tariffs_supply',
        'Коэффициенты приёмки на складах WB',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'wb_tariffs_supply',
        existing_comment='Коэффициенты приёмки на складах WB',
        schema=None
    )
    op.alter_column('wb_tariffs_supply', 'box_type_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Тип поставки: 2=Короба, 5=Паллеты, 6=Суперсейф',
               existing_nullable=True)
    op.alter_column('wb_tariffs_supply', 'allow_unload',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Доступность приёмки',
               existing_nullable=True)
    op.alter_column('wb_tariffs_supply', 'date',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Дата начала действия',
               existing_nullable=True)
    op.add_column('wb_tariffs_pallet', sa.Column('warehouse_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='ID склада WB'))
    op.drop_index(op.f('ix_wb_tariffs_pallet_warehouse_name'), table_name='wb_tariffs_pallet')
    op.create_unique_constraint(op.f('uq_tariffs_pallet_warehouse_name'), 'wb_tariffs_pallet', ['warehouse_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_wb_tariffs_pallet_warehouse_id'), 'wb_tariffs_pallet', ['warehouse_id'], unique=False)
    op.alter_column('wb_tariffs_pallet', 'warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Название склада')
    op.drop_index(op.f('ix_wb_tariffs_commission_subject_id'), table_name='wb_tariffs_commission')
    op.create_index(op.f('ix_wb_tariffs_commission_subject_id'), 'wb_tariffs_commission', ['subject_id'], unique=False)
    op.create_unique_constraint(op.f('uq_tariffs_commission_subject_id'), 'wb_tariffs_commission', ['subject_id'], postgresql_nulls_not_distinct=False)
    op.add_column('wb_tariffs_box', sa.Column('dt_next_box', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Дата пересчёта'))
    op.add_column('wb_tariffs_box', sa.Column('box_delivery_additional_liter', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Доп. литр доставки, руб.'))
    op.add_column('wb_tariffs_box', sa.Column('box_storage_additional_liter', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True, comment='Доп. литр хранения, руб./день'))
    op.add_column('wb_tariffs_box', sa.Column('warehouse_id', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='ID склада WB'))
    op.drop_index(op.f('ix_wb_tariffs_box_warehouse_name'), table_name='wb_tariffs_box')
    op.create_unique_constraint(op.f('uq_tariffs_box_warehouse_name'), 'wb_tariffs_box', ['warehouse_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_wb_tariffs_box_warehouse_id'), 'wb_tariffs_box', ['warehouse_id'], unique=False)
    op.alter_column('wb_tariffs_box', 'box_storage_liter',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Тариф хранения за литр, руб./день',
               existing_comment='Хранение в день, дополнительный литр, руб.',
               existing_nullable=True)
    op.alter_column('wb_tariffs_box', 'box_storage_base',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Базовый тариф хранения, руб./день',
               existing_comment='Хранение в день, первый литр, руб.',
               existing_nullable=True)
    op.alter_column('wb_tariffs_box', 'box_delivery_liter',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Тариф доставки за литр, руб.',
               existing_comment='Логистика, дополнительный литр, руб.',
               existing_nullable=True)
    op.alter_column('wb_tariffs_box', 'box_delivery_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Базовый тариф доставки, руб.',
               existing_comment='Логистика, первый литр, руб.',
               existing_nullable=True)
    op.alter_column('wb_tariffs_box', 'warehouse_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Название склада')
    op.alter_column('wb_seller_subscriptions', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('wb_seller_rating', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_wb_prices_nm_id'), table_name='wb_prices')
    op.create_index(op.f('ix_wb_prices_nm_id'), 'wb_prices', ['nm_id'], unique=False)
    # ### end Alembic commands ###
