"""init: sellers table

Revision ID: 3ca00228cdb1
Revises: 
Create Date: 2026-03-16 22:33:18.240456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ca00228cdb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('trade_mark', sa.String(length=500), nullable=False),
    sa.Column('itn', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_sid'), 'sellers', ['sid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_sid'), table_name='sellers')
    op.drop_table('sellers')
    # ### end Alembic commands ###
