"""add_users_table

Revision ID: 89e199b021cd
Revises: defac75f119b
Create Date: 2026-04-03 15:22:07.843212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89e199b021cd'
down_revision: Union[str, None] = 'defac75f119b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('second_name', sa.String(length=200), nullable=True),
    sa.Column('patronymic', sa.String(length=200), nullable=True),
    sa.Column('goods_return', sa.Boolean(), nullable=True),
    sa.Column('is_invitee', sa.Boolean(), nullable=True),
    sa.Column('invitee_info', sa.JSON(), nullable=True),
    sa.Column('access', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_wb_news_date'), table_name='news')
    op.drop_index(op.f('ix_wb_news_news_id'), table_name='news')
    op.create_index(op.f('ix_news_date'), 'news', ['date'], unique=False)
    op.create_index(op.f('ix_news_news_id'), 'news', ['news_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_news_id'), table_name='news')
    op.drop_index(op.f('ix_news_date'), table_name='news')
    op.create_index(op.f('ix_wb_news_news_id'), 'news', ['news_id'], unique=True)
    op.create_index(op.f('ix_wb_news_date'), 'news', ['date'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###
