"""add_all_wb_tables_and_news

Revision ID: 9aba171a7828
Revises: 3ca00228cdb1
Create Date: 2026-03-21 10:04:32.749362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9aba171a7828'
down_revision: Union[str, None] = '3ca00228cdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbs_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='ID заказа'),
    sa.Column('order_uid', sa.String(length=100), nullable=True, comment='UUID заказа'),
    sa.Column('rid', sa.String(length=100), nullable=True, comment='ID позиции'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Дата создания'),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=True, comment='Дата изменения'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Склад WB'),
    sa.Column('country_name', sa.String(length=100), nullable=True, comment='Страна'),
    sa.Column('region_name', sa.String(length=255), nullable=True, comment='Регион'),
    sa.Column('article', sa.String(length=100), nullable=True, comment='Артикул продавца'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('chrt_id', sa.BigInteger(), nullable=True, comment='ID размера'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Предмет'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Категория'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Бренд'),
    sa.Column('name', sa.String(length=500), nullable=True, comment='Наименование'),
    sa.Column('tech_size', sa.String(length=50), nullable=True, comment='Размер'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена, руб.'),
    sa.Column('discount_percent', sa.Integer(), nullable=True, comment='Скидка, %'),
    sa.Column('finished_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Итоговая цена, руб.'),
    sa.Column('is_cancel', sa.Boolean(), nullable=False, comment='Отменён'),
    sa.Column('cancel_date', sa.DateTime(timezone=True), nullable=True, comment='Дата отмены'),
    sa.Column('order_type', sa.String(length=100), nullable=True, comment='Тип заказа'),
    sa.Column('supplier_status', sa.String(length=50), nullable=True, comment='Статус продавца'),
    sa.Column('wb_status', sa.String(length=50), nullable=True, comment='Статус WB'),
    sa.Column('delivery_address', sa.String(length=500), nullable=True, comment='Адрес доставки (JSON)'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbs_orders_date'), 'dbs_orders', ['date'], unique=False)
    op.create_index(op.f('ix_dbs_orders_nm_id'), 'dbs_orders', ['nm_id'], unique=False)
    op.create_index(op.f('ix_dbs_orders_order_id'), 'dbs_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_dbs_orders_order_uid'), 'dbs_orders', ['order_uid'], unique=False)
    op.create_table('dbw_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='ID заказа'),
    sa.Column('order_uid', sa.String(length=100), nullable=True, comment='UUID заказа'),
    sa.Column('rid', sa.String(length=100), nullable=True, comment='ID позиции заказа'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Дата создания'),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=True, comment='Дата изменения статуса'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Склад WB'),
    sa.Column('country_name', sa.String(length=100), nullable=True, comment='Страна'),
    sa.Column('region_name', sa.String(length=255), nullable=True, comment='Регион'),
    sa.Column('article', sa.String(length=100), nullable=True, comment='Артикул продавца'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('chrt_id', sa.BigInteger(), nullable=True, comment='ID размера'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Предмет'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Категория'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Бренд'),
    sa.Column('name', sa.String(length=500), nullable=True, comment='Наименование'),
    sa.Column('tech_size', sa.String(length=50), nullable=True, comment='Размер'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена, руб.'),
    sa.Column('discount_percent', sa.Integer(), nullable=True, comment='Скидка, %'),
    sa.Column('finished_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Итоговая цена, руб.'),
    sa.Column('is_cancel', sa.Boolean(), nullable=False, comment='Отменён'),
    sa.Column('cancel_date', sa.DateTime(timezone=True), nullable=True, comment='Дата отмены'),
    sa.Column('order_type', sa.String(length=100), nullable=True, comment='Тип заказа'),
    sa.Column('supplier_status', sa.String(length=50), nullable=True, comment='Статус продавца'),
    sa.Column('wb_status', sa.String(length=50), nullable=True, comment='Статус WB'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbw_orders_date'), 'dbw_orders', ['date'], unique=False)
    op.create_index(op.f('ix_dbw_orders_nm_id'), 'dbw_orders', ['nm_id'], unique=False)
    op.create_index(op.f('ix_dbw_orders_order_id'), 'dbw_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_dbw_orders_order_uid'), 'dbw_orders', ['order_uid'], unique=False)
    op.create_table('fbs_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='ID сборочного задания'),
    sa.Column('order_uid', sa.String(length=100), nullable=True, comment='UUID заказа'),
    sa.Column('rid', sa.String(length=100), nullable=True, comment='Уникальный ID позиции заказа'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Дата создания заказа'),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=True, comment='Дата последнего изменения статуса'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Склад WB отгрузки'),
    sa.Column('country_name', sa.String(length=100), nullable=True, comment='Страна доставки'),
    sa.Column('oblast_okrug_name', sa.String(length=255), nullable=True, comment='Федеральный округ'),
    sa.Column('region_name', sa.String(length=255), nullable=True, comment='Регион доставки'),
    sa.Column('article', sa.String(length=100), nullable=True, comment='Артикул продавца'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('chrt_id', sa.BigInteger(), nullable=True, comment='ID характеристики размера'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Предмет'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Категория'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Бренд'),
    sa.Column('name', sa.String(length=500), nullable=True, comment='Наименование товара'),
    sa.Column('tech_size', sa.String(length=50), nullable=True, comment='Технический размер'),
    sa.Column('color_code', sa.String(length=50), nullable=True, comment='Код цвета'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена без скидок, руб.'),
    sa.Column('discount_percent', sa.Integer(), nullable=True, comment='Скидка продавца, %'),
    sa.Column('spp', sa.Integer(), nullable=True, comment='Скидка по программе WB (СПП), %'),
    sa.Column('finished_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Итоговая цена, руб.'),
    sa.Column('price_with_disc', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена со скидкой продавца, руб.'),
    sa.Column('is_cancel', sa.Boolean(), nullable=False, comment='Отменён'),
    sa.Column('cancel_date', sa.DateTime(timezone=True), nullable=True, comment='Дата отмены'),
    sa.Column('order_type', sa.String(length=100), nullable=True, comment='Тип заказа'),
    sa.Column('supplier_status', sa.String(length=50), nullable=True, comment='Статус продавца'),
    sa.Column('wb_status', sa.String(length=50), nullable=True, comment='Статус WB'),
    sa.Column('skus', sa.JSON(), nullable=True, comment='Баркоды товара (JSON)'),
    sa.Column('is_zero_order', sa.Boolean(), nullable=False, comment='Нулевой заказ'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fbs_orders_date'), 'fbs_orders', ['date'], unique=False)
    op.create_index(op.f('ix_fbs_orders_nm_id'), 'fbs_orders', ['nm_id'], unique=False)
    op.create_index(op.f('ix_fbs_orders_order_id'), 'fbs_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_fbs_orders_order_uid'), 'fbs_orders', ['order_uid'], unique=False)
    op.create_table('pickup_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='ID заказа'),
    sa.Column('order_uid', sa.String(length=100), nullable=True, comment='UUID заказа'),
    sa.Column('rid', sa.String(length=100), nullable=True, comment='ID позиции'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Дата создания'),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=True, comment='Дата изменения'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Склад WB'),
    sa.Column('article', sa.String(length=100), nullable=True, comment='Артикул продавца'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Предмет'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Категория'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Бренд'),
    sa.Column('name', sa.String(length=500), nullable=True, comment='Наименование'),
    sa.Column('tech_size', sa.String(length=50), nullable=True, comment='Размер'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена, руб.'),
    sa.Column('discount_percent', sa.Integer(), nullable=True, comment='Скидка, %'),
    sa.Column('finished_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Итоговая цена, руб.'),
    sa.Column('is_cancel', sa.Boolean(), nullable=False, comment='Отменён'),
    sa.Column('cancel_date', sa.DateTime(timezone=True), nullable=True, comment='Дата отмены'),
    sa.Column('supplier_status', sa.String(length=50), nullable=True, comment='Статус продавца'),
    sa.Column('wb_status', sa.String(length=50), nullable=True, comment='Статус WB'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_orders_date'), 'pickup_orders', ['date'], unique=False)
    op.create_index(op.f('ix_pickup_orders_nm_id'), 'pickup_orders', ['nm_id'], unique=False)
    op.create_index(op.f('ix_pickup_orders_order_id'), 'pickup_orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_pickup_orders_order_uid'), 'pickup_orders', ['order_uid'], unique=False)
    op.create_table('wb_campaign_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advert_id', sa.BigInteger(), nullable=False, comment='ID кампании'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Дата'),
    sa.Column('views', sa.BigInteger(), nullable=True, comment='Показы'),
    sa.Column('clicks', sa.Integer(), nullable=True, comment='Клики'),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True, comment='CTR, %'),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True, comment='CPC, руб.'),
    sa.Column('sum', sa.Numeric(precision=12, scale=2), nullable=True, comment='Расходы, руб.'),
    sa.Column('atbs', sa.Integer(), nullable=True, comment='Добавления в корзину'),
    sa.Column('orders', sa.Integer(), nullable=True, comment='Заказы'),
    sa.Column('cr', sa.Numeric(precision=8, scale=4), nullable=True, comment='CR (конверсия в заказ), %'),
    sa.Column('shks', sa.Integer(), nullable=True, comment='Заказано товаров, шт.'),
    sa.Column('sum_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Заказано на сумму, руб.'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='Полные данные (JSON)'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_campaign_stats_advert_id'), 'wb_campaign_stats', ['advert_id'], unique=False)
    op.create_index(op.f('ix_wb_campaign_stats_date'), 'wb_campaign_stats', ['date'], unique=False)
    op.create_table('wb_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advert_id', sa.BigInteger(), nullable=False, comment='ID кампании'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Название кампании'),
    sa.Column('status', sa.Integer(), nullable=True, comment='-1=удалена,4=готова,7=завершена,8=отказ,9=показы,11=пауза'),
    sa.Column('type', sa.Integer(), nullable=True, comment='4=каталог,5=карточка,6=поиск,7=рекомендации,9=авто'),
    sa.Column('payment_type', sa.String(length=20), nullable=True, comment='cpm или cpc'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=True, comment='Дата создания'),
    sa.Column('change_time', sa.DateTime(timezone=True), nullable=True, comment='Дата изменения'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='Дата запуска'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='Дата завершения'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_campaigns_advert_id'), 'wb_campaigns', ['advert_id'], unique=True)
    op.create_index(op.f('ix_wb_campaigns_status'), 'wb_campaigns', ['status'], unique=False)
    op.create_table('wb_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False, comment='Артикул WB (nmID)'),
    sa.Column('imt_id', sa.BigInteger(), nullable=True, comment='ID предмета (группа карточек одного товара)'),
    sa.Column('nm_uuid', sa.String(length=100), nullable=True, comment='UUID карточки'),
    sa.Column('subject_id', sa.Integer(), nullable=True, comment='ID подкатегории'),
    sa.Column('subject_name', sa.String(length=255), nullable=True, comment='Название подкатегории'),
    sa.Column('vendor_code', sa.String(length=100), nullable=True, comment='Артикул продавца'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Бренд'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='Наименование товара'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание товара'),
    sa.Column('in_trash', sa.Boolean(), nullable=False, comment='В корзине'),
    sa.Column('length', sa.Float(), nullable=True, comment='Длина упаковки, см'),
    sa.Column('width', sa.Float(), nullable=True, comment='Ширина упаковки, см'),
    sa.Column('height', sa.Float(), nullable=True, comment='Высота упаковки, см'),
    sa.Column('weight_brutto', sa.Float(), nullable=True, comment='Вес брутто, кг'),
    sa.Column('sizes', sa.JSON(), nullable=True, comment='Размеры и SKU (JSON)'),
    sa.Column('characteristics', sa.JSON(), nullable=True, comment='Характеристики карточки (JSON)'),
    sa.Column('photos', sa.JSON(), nullable=True, comment='Фотографии карточки (JSON)'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='Теги карточки (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='Дата создания карточки'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Дата обновления карточки'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_cards_nm_id'), 'wb_cards', ['nm_id'], unique=True)
    op.create_index(op.f('ix_wb_cards_vendor_code'), 'wb_cards', ['vendor_code'], unique=False)
    op.create_table('wb_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=100), nullable=False, comment='ID претензии'),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True, comment='Дата создания'),
    sa.Column('state', sa.String(length=50), nullable=True, comment='Статус претензии'),
    sa.Column('text', sa.Text(), nullable=True, comment='Текст претензии'),
    sa.Column('user_name', sa.String(length=255), nullable=True, comment='Имя покупателя'),
    sa.Column('answer_text', sa.Text(), nullable=True, comment='Текст ответа продавца'),
    sa.Column('product_details', sa.JSON(), nullable=True, comment='Данные товара (JSON)'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_claims_claim_id'), 'wb_claims', ['claim_id'], unique=True)
    op.create_index(op.f('ix_wb_claims_created_date'), 'wb_claims', ['created_date'], unique=False)
    op.create_table('wb_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.String(length=100), nullable=False, comment='ID отзыва'),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True, comment='Дата создания'),
    sa.Column('product_valuation', sa.Integer(), nullable=True, comment='Оценка товара 1–5'),
    sa.Column('was_viewed', sa.Boolean(), nullable=True, comment='Просмотрен'),
    sa.Column('text', sa.Text(), nullable=True, comment='Текст отзыва'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('supplier_article', sa.String(length=100), nullable=True, comment='Артикул продавца'),
    sa.Column('subject_name', sa.String(length=255), nullable=True, comment='Предмет'),
    sa.Column('answer_text', sa.Text(), nullable=True, comment='Текст ответа продавца'),
    sa.Column('answer_state', sa.String(length=50), nullable=True, comment='Статус ответа'),
    sa.Column('user_name', sa.String(length=255), nullable=True, comment='Имя покупателя'),
    sa.Column('is_able_to_change_grade', sa.Boolean(), nullable=True, comment='Можно изменить оценку'),
    sa.Column('photo', sa.JSON(), nullable=True, comment='Фото в отзыве (JSON)'),
    sa.Column('video', sa.JSON(), nullable=True, comment='Видео в отзыве (JSON)'),
    sa.Column('product_details', sa.JSON(), nullable=True, comment='Данные товара (JSON)'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_feedbacks_created_date'), 'wb_feedbacks', ['created_date'], unique=False)
    op.create_index(op.f('ix_wb_feedbacks_feedback_id'), 'wb_feedbacks', ['feedback_id'], unique=True)
    op.create_index(op.f('ix_wb_feedbacks_nm_id'), 'wb_feedbacks', ['nm_id'], unique=False)
    op.create_table('wb_financial_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rrd_id', sa.BigInteger(), nullable=False, comment='ID строки отчёта'),
    sa.Column('realizationreport_id', sa.BigInteger(), nullable=True, comment='ID отчёта о реализации'),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True, comment='Дата начала периода'),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=True, comment='Дата окончания периода'),
    sa.Column('create_dt', sa.DateTime(timezone=True), nullable=True, comment='Дата формирования отчёта'),
    sa.Column('supplier_name', sa.String(length=255), nullable=True, comment='Наименование поставщика'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('brand_name', sa.String(length=255), nullable=True, comment='Бренд'),
    sa.Column('sa_name', sa.String(length=100), nullable=True, comment='Артикул продавца'),
    sa.Column('ts_name', sa.String(length=50), nullable=True, comment='Размер'),
    sa.Column('barcode', sa.String(length=50), nullable=True, comment='Баркод'),
    sa.Column('subject_name', sa.String(length=255), nullable=True, comment='Предмет'),
    sa.Column('doc_type_name', sa.String(length=100), nullable=True, comment='Тип документа'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='Количество'),
    sa.Column('retail_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Розничная цена, руб.'),
    sa.Column('retail_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Сумма продаж, руб.'),
    sa.Column('sale_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Согласованная скидка, %'),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Комиссия WB, %'),
    sa.Column('office_name', sa.String(length=255), nullable=True, comment='Офис/склад доставки'),
    sa.Column('supplier_oper_name', sa.String(length=255), nullable=True, comment='Обоснование для оплаты'),
    sa.Column('order_dt', sa.DateTime(timezone=True), nullable=True, comment='Дата заказа'),
    sa.Column('sale_dt', sa.DateTime(timezone=True), nullable=True, comment='Дата продажи'),
    sa.Column('rr_dt', sa.DateTime(timezone=True), nullable=True, comment='Дата операции'),
    sa.Column('retail_price_withdisc_rub', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена с согласованной скидкой, руб.'),
    sa.Column('delivery_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Количество доставок'),
    sa.Column('return_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Количество возвратов'),
    sa.Column('delivery_rub', sa.Numeric(precision=12, scale=2), nullable=True, comment='Стоимость логистики, руб.'),
    sa.Column('ppvz_for_pay', sa.Numeric(precision=12, scale=2), nullable=True, comment='К перечислению продавцу, руб.'),
    sa.Column('ppvz_reward', sa.Numeric(precision=12, scale=2), nullable=True, comment='Вознаграждение WB, руб.'),
    sa.Column('ppvz_sales_commission', sa.Numeric(precision=12, scale=2), nullable=True, comment='Вознаграждение с продаж, руб.'),
    sa.Column('ppvz_vw', sa.Numeric(precision=12, scale=2), nullable=True, comment='Вознаграждение WB без НДС, руб.'),
    sa.Column('ppvz_vw_nds', sa.Numeric(precision=12, scale=2), nullable=True, comment='НДС с вознаграждения WB, руб.'),
    sa.Column('acquiring_fee', sa.Numeric(precision=12, scale=2), nullable=True, comment='Расходы на эквайринг, руб.'),
    sa.Column('penalty', sa.Numeric(precision=12, scale=2), nullable=True, comment='Штрафы, руб.'),
    sa.Column('additional_payment', sa.Numeric(precision=12, scale=2), nullable=True, comment='Доплаты, руб.'),
    sa.Column('storage_fee', sa.Numeric(precision=12, scale=2), nullable=True, comment='Стоимость хранения, руб.'),
    sa.Column('deduction', sa.Numeric(precision=12, scale=2), nullable=True, comment='Прочие удержания, руб.'),
    sa.Column('acceptance', sa.Numeric(precision=12, scale=2), nullable=True, comment='Стоимость платной приёмки, руб.'),
    sa.Column('rebill_logistic_cost', sa.Numeric(precision=12, scale=2), nullable=True, comment='Возвратная логистика, руб.'),
    sa.Column('site_country', sa.String(length=50), nullable=True, comment='Страна продажи'),
    sa.Column('srid', sa.String(length=100), nullable=True, comment='Уникальный ID заказа'),
    sa.Column('gi_id', sa.BigInteger(), nullable=True, comment='ID поставки'),
    sa.Column('rid', sa.BigInteger(), nullable=True, comment='ID заказа'),
    sa.Column('kiz', sa.String(length=100), nullable=True, comment='КИЗ маркировки'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_financial_report_barcode'), 'wb_financial_report', ['barcode'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_nm_id'), 'wb_financial_report', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_order_dt'), 'wb_financial_report', ['order_dt'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_realizationreport_id'), 'wb_financial_report', ['realizationreport_id'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_rrd_id'), 'wb_financial_report', ['rrd_id'], unique=True)
    op.create_index(op.f('ix_wb_financial_report_sale_dt'), 'wb_financial_report', ['sale_dt'], unique=False)
    op.create_index(op.f('ix_wb_financial_report_srid'), 'wb_financial_report', ['srid'], unique=False)
    op.create_table('wb_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False, comment='ID новости'),
    sa.Column('header', sa.String(length=500), nullable=True, comment='Заголовок новости'),
    sa.Column('content', sa.Text(), nullable=True, comment='Текст новости (HTML)'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Дата публикации'),
    sa.Column('types', sa.JSON(), nullable=True, comment='Теги новости [{id, name}]'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_news_date'), 'wb_news', ['date'], unique=False)
    op.create_index(op.f('ix_wb_news_news_id'), 'wb_news', ['news_id'], unique=True)
    op.create_table('wb_orders_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('odid', sa.BigInteger(), nullable=True, comment='ID уникальной позиции заказа'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Дата заказа'),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=True, comment='Дата последнего изменения'),
    sa.Column('supplier_article', sa.String(length=100), nullable=True, comment='Артикул поставщика'),
    sa.Column('tech_size', sa.String(length=50), nullable=True, comment='Размер'),
    sa.Column('barcode', sa.String(length=50), nullable=True, comment='Баркод'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена до скидки, руб.'),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Скидка продавца, %'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Склад WB'),
    sa.Column('oblast', sa.String(length=255), nullable=True, comment='Регион доставки'),
    sa.Column('income_id', sa.BigInteger(), nullable=True, comment='ID поставки'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Предмет'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Категория'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Бренд'),
    sa.Column('is_cancel', sa.Boolean(), nullable=True, comment='Отменён'),
    sa.Column('cancel_date', sa.DateTime(timezone=True), nullable=True, comment='Дата отмены'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_orders_report_barcode'), 'wb_orders_report', ['barcode'], unique=False)
    op.create_index(op.f('ix_wb_orders_report_date'), 'wb_orders_report', ['date'], unique=False)
    op.create_index(op.f('ix_wb_orders_report_nm_id'), 'wb_orders_report', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_orders_report_odid'), 'wb_orders_report', ['odid'], unique=True)
    op.create_table('wb_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nm_id', sa.BigInteger(), nullable=False, comment='Артикул WB (nmID)'),
    sa.Column('vendor_code', sa.String(length=100), nullable=True, comment='Артикул продавца'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена до скидки, руб.'),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True, comment='Скидка продавца, %'),
    sa.Column('discounted_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена со скидкой, руб.'),
    sa.Column('club_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена клуба WB, руб.'),
    sa.Column('currency_iso_code', sa.String(length=10), nullable=True, comment='Код валюты ISO'),
    sa.Column('editable', sa.Boolean(), nullable=True, comment='Доступна ли цена для изменения'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_prices_nm_id'), 'wb_prices', ['nm_id'], unique=False)
    op.create_table('wb_promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_id', sa.BigInteger(), nullable=False, comment='ID акции'),
    sa.Column('name', sa.String(length=500), nullable=True, comment='Название акции'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='Дата начала'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='Дата окончания'),
    sa.Column('type', sa.String(length=100), nullable=True, comment='Тип акции'),
    sa.Column('in_action', sa.Boolean(), nullable=True, comment='Участвует ли продавец'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_promotions_promotion_id'), 'wb_promotions', ['promotion_id'], unique=True)
    op.create_table('wb_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.String(length=100), nullable=False, comment='ID вопроса'),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True, comment='Дата создания'),
    sa.Column('state', sa.String(length=50), nullable=True, comment='Статус: none=новый, wbRu=отвечен WB, answered=отвечен продавцом'),
    sa.Column('text', sa.Text(), nullable=True, comment='Текст вопроса'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('answer_text', sa.Text(), nullable=True, comment='Текст ответа'),
    sa.Column('user_name', sa.String(length=255), nullable=True, comment='Имя покупателя'),
    sa.Column('product_details', sa.JSON(), nullable=True, comment='Данные товара (JSON)'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_questions_created_date'), 'wb_questions', ['created_date'], unique=False)
    op.create_index(op.f('ix_wb_questions_nm_id'), 'wb_questions', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_questions_question_id'), 'wb_questions', ['question_id'], unique=True)
    op.create_table('wb_sales_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('srid', sa.String(length=100), nullable=True, comment='Уникальный ID продажи/возврата'),
    sa.Column('sale_id', sa.String(length=50), nullable=True, comment='S = продажа, R = возврат'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Дата продажи/возврата'),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=True, comment='Дата изменения'),
    sa.Column('supplier_article', sa.String(length=100), nullable=True, comment='Артикул поставщика'),
    sa.Column('tech_size', sa.String(length=50), nullable=True, comment='Размер'),
    sa.Column('barcode', sa.String(length=50), nullable=True, comment='Баркод'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена до скидки, руб.'),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Скидка, %'),
    sa.Column('is_supply', sa.Boolean(), nullable=True, comment='Тип операции: поставка'),
    sa.Column('is_realization', sa.Boolean(), nullable=True, comment='Тип операции: реализация'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Склад WB'),
    sa.Column('oblast', sa.String(length=255), nullable=True, comment='Регион'),
    sa.Column('income_id', sa.BigInteger(), nullable=True, comment='ID поставки'),
    sa.Column('odid', sa.BigInteger(), nullable=True, comment='ID позиции заказа'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Предмет'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Категория'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Бренд'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_sales_report_barcode'), 'wb_sales_report', ['barcode'], unique=False)
    op.create_index(op.f('ix_wb_sales_report_date'), 'wb_sales_report', ['date'], unique=False)
    op.create_index(op.f('ix_wb_sales_report_nm_id'), 'wb_sales_report', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_sales_report_odid'), 'wb_sales_report', ['odid'], unique=False)
    op.create_index(op.f('ix_wb_sales_report_sale_id'), 'wb_sales_report', ['sale_id'], unique=False)
    op.create_index(op.f('ix_wb_sales_report_srid'), 'wb_sales_report', ['srid'], unique=True)
    op.create_table('wb_seller_warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='ID склада'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Название склада'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='Адрес склада'),
    sa.Column('work_time', sa.String(length=100), nullable=True, comment='Режим работы'),
    sa.Column('selected_coefficient', sa.Integer(), nullable=True, comment='Коэффициент склада'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id')
    )
    op.create_table('wb_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_change_date', sa.DateTime(timezone=True), nullable=True, comment='Дата последнего изменения'),
    sa.Column('supplier_article', sa.String(length=100), nullable=True, comment='Артикул поставщика'),
    sa.Column('tech_size', sa.String(length=50), nullable=True, comment='Размер'),
    sa.Column('barcode', sa.String(length=50), nullable=True, comment='Баркод'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='Количество на складе WB'),
    sa.Column('is_supply', sa.Boolean(), nullable=True, comment='Признак поставки FBO'),
    sa.Column('is_realization', sa.Boolean(), nullable=True, comment='Признак реализации'),
    sa.Column('quantity_full', sa.Integer(), nullable=True, comment='Полное количество (с браком)'),
    sa.Column('in_way_to_client', sa.Integer(), nullable=True, comment='В пути к покупателю'),
    sa.Column('in_way_from_client', sa.Integer(), nullable=True, comment='В пути от покупателя'),
    sa.Column('nm_id', sa.BigInteger(), nullable=True, comment='Артикул WB (nmID)'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Предмет'),
    sa.Column('category', sa.String(length=255), nullable=True, comment='Категория'),
    sa.Column('brand', sa.String(length=255), nullable=True, comment='Бренд'),
    sa.Column('sc_code', sa.String(length=50), nullable=True, comment='Код WB склада'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True, comment='Цена товара, руб.'),
    sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True, comment='Скидка, %'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Название склада'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_stocks_barcode'), 'wb_stocks', ['barcode'], unique=False)
    op.create_index(op.f('ix_wb_stocks_last_change_date'), 'wb_stocks', ['last_change_date'], unique=False)
    op.create_index(op.f('ix_wb_stocks_nm_id'), 'wb_stocks', ['nm_id'], unique=False)
    op.create_index(op.f('ix_wb_stocks_warehouse_name'), 'wb_stocks', ['warehouse_name'], unique=False)
    op.create_table('wb_sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False, comment='Название модуля синхронизации'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Дата последней успешной синхронизации'),
    sa.Column('last_cursor', sa.String(length=255), nullable=True, comment='Курсор пагинации (rrdid, offset и т.д.)'),
    sa.Column('records_total', sa.BigInteger(), nullable=True, comment='Всего записей в БД'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='ok / error / running'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='Сообщение об ошибке'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_sync_state_module'), 'wb_sync_state', ['module'], unique=True)
    op.create_table('wb_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='ID тега WB'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название тега'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='Цвет тега (HEX)'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id')
    )
    op.create_table('wb_tariffs_box',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='ID склада WB'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Название склада'),
    sa.Column('dt_next_box', sa.DateTime(timezone=True), nullable=True, comment='Дата пересчёта'),
    sa.Column('box_delivery_base', sa.Numeric(precision=10, scale=2), nullable=True, comment='Базовый тариф доставки, руб.'),
    sa.Column('box_delivery_liter', sa.Numeric(precision=10, scale=2), nullable=True, comment='Тариф доставки за литр, руб.'),
    sa.Column('box_delivery_additional_liter', sa.Numeric(precision=10, scale=2), nullable=True, comment='Доп. литр доставки, руб.'),
    sa.Column('box_storage_base', sa.Numeric(precision=10, scale=4), nullable=True, comment='Базовый тариф хранения, руб./день'),
    sa.Column('box_storage_liter', sa.Numeric(precision=10, scale=4), nullable=True, comment='Тариф хранения за литр, руб./день'),
    sa.Column('box_storage_additional_liter', sa.Numeric(precision=10, scale=4), nullable=True, comment='Доп. литр хранения, руб./день'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_tariffs_box_warehouse_id'), 'wb_tariffs_box', ['warehouse_id'], unique=False)
    op.create_table('wb_tariffs_commission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True, comment='ID категории'),
    sa.Column('subject_name', sa.String(length=255), nullable=True, comment='Название категории (предмет)'),
    sa.Column('parent_name', sa.String(length=255), nullable=True, comment='Родительская категория'),
    sa.Column('kgvp_marketplace', sa.Numeric(precision=5, scale=2), nullable=True, comment='Комиссия маркетплейс, %'),
    sa.Column('kgvp_supplier', sa.Numeric(precision=5, scale=2), nullable=True, comment='Комиссия поставщик, %'),
    sa.Column('kgvp_supplier_express', sa.Numeric(precision=5, scale=2), nullable=True, comment='Комиссия экспресс, %'),
    sa.Column('return_cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='Стоимость возврата покупателя'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_tariffs_commission_subject_id'), 'wb_tariffs_commission', ['subject_id'], unique=False)
    op.create_table('wb_tariffs_pallet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='ID склада WB'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Название склада'),
    sa.Column('is_super_safe', sa.Boolean(), nullable=True, comment='Повышенная безопасность хранения'),
    sa.Column('pallet_delivery_value_base', sa.Numeric(precision=10, scale=2), nullable=True, comment='Базовый тариф доставки паллеты, руб.'),
    sa.Column('pallet_delivery_value_liter', sa.Numeric(precision=10, scale=2), nullable=True, comment='Тариф за литр, руб.'),
    sa.Column('pallet_storage_value', sa.Numeric(precision=10, scale=4), nullable=True, comment='Тариф хранения паллеты, руб./день'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_tariffs_pallet_warehouse_id'), 'wb_tariffs_pallet', ['warehouse_id'], unique=False)
    op.create_table('wb_tariffs_supply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='ID склада WB'),
    sa.Column('warehouse_name', sa.String(length=255), nullable=True, comment='Название склада'),
    sa.Column('coefficient', sa.Integer(), nullable=True, comment='Коэффициент: 0=бесплатно, -1=закрыт'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Дата синхронизации'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wb_tariffs_supply_warehouse_id'), 'wb_tariffs_supply', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wb_tariffs_supply_warehouse_id'), table_name='wb_tariffs_supply')
    op.drop_table('wb_tariffs_supply')
    op.drop_index(op.f('ix_wb_tariffs_pallet_warehouse_id'), table_name='wb_tariffs_pallet')
    op.drop_table('wb_tariffs_pallet')
    op.drop_index(op.f('ix_wb_tariffs_commission_subject_id'), table_name='wb_tariffs_commission')
    op.drop_table('wb_tariffs_commission')
    op.drop_index(op.f('ix_wb_tariffs_box_warehouse_id'), table_name='wb_tariffs_box')
    op.drop_table('wb_tariffs_box')
    op.drop_table('wb_tags')
    op.drop_index(op.f('ix_wb_sync_state_module'), table_name='wb_sync_state')
    op.drop_table('wb_sync_state')
    op.drop_index(op.f('ix_wb_stocks_warehouse_name'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_nm_id'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_last_change_date'), table_name='wb_stocks')
    op.drop_index(op.f('ix_wb_stocks_barcode'), table_name='wb_stocks')
    op.drop_table('wb_stocks')
    op.drop_table('wb_seller_warehouses')
    op.drop_index(op.f('ix_wb_sales_report_srid'), table_name='wb_sales_report')
    op.drop_index(op.f('ix_wb_sales_report_sale_id'), table_name='wb_sales_report')
    op.drop_index(op.f('ix_wb_sales_report_odid'), table_name='wb_sales_report')
    op.drop_index(op.f('ix_wb_sales_report_nm_id'), table_name='wb_sales_report')
    op.drop_index(op.f('ix_wb_sales_report_date'), table_name='wb_sales_report')
    op.drop_index(op.f('ix_wb_sales_report_barcode'), table_name='wb_sales_report')
    op.drop_table('wb_sales_report')
    op.drop_index(op.f('ix_wb_questions_question_id'), table_name='wb_questions')
    op.drop_index(op.f('ix_wb_questions_nm_id'), table_name='wb_questions')
    op.drop_index(op.f('ix_wb_questions_created_date'), table_name='wb_questions')
    op.drop_table('wb_questions')
    op.drop_index(op.f('ix_wb_promotions_promotion_id'), table_name='wb_promotions')
    op.drop_table('wb_promotions')
    op.drop_index(op.f('ix_wb_prices_nm_id'), table_name='wb_prices')
    op.drop_table('wb_prices')
    op.drop_index(op.f('ix_wb_orders_report_odid'), table_name='wb_orders_report')
    op.drop_index(op.f('ix_wb_orders_report_nm_id'), table_name='wb_orders_report')
    op.drop_index(op.f('ix_wb_orders_report_date'), table_name='wb_orders_report')
    op.drop_index(op.f('ix_wb_orders_report_barcode'), table_name='wb_orders_report')
    op.drop_table('wb_orders_report')
    op.drop_index(op.f('ix_wb_news_news_id'), table_name='wb_news')
    op.drop_index(op.f('ix_wb_news_date'), table_name='wb_news')
    op.drop_table('wb_news')
    op.drop_index(op.f('ix_wb_financial_report_srid'), table_name='wb_financial_report')
    op.drop_index(op.f('ix_wb_financial_report_sale_dt'), table_name='wb_financial_report')
    op.drop_index(op.f('ix_wb_financial_report_rrd_id'), table_name='wb_financial_report')
    op.drop_index(op.f('ix_wb_financial_report_realizationreport_id'), table_name='wb_financial_report')
    op.drop_index(op.f('ix_wb_financial_report_order_dt'), table_name='wb_financial_report')
    op.drop_index(op.f('ix_wb_financial_report_nm_id'), table_name='wb_financial_report')
    op.drop_index(op.f('ix_wb_financial_report_barcode'), table_name='wb_financial_report')
    op.drop_table('wb_financial_report')
    op.drop_index(op.f('ix_wb_feedbacks_nm_id'), table_name='wb_feedbacks')
    op.drop_index(op.f('ix_wb_feedbacks_feedback_id'), table_name='wb_feedbacks')
    op.drop_index(op.f('ix_wb_feedbacks_created_date'), table_name='wb_feedbacks')
    op.drop_table('wb_feedbacks')
    op.drop_index(op.f('ix_wb_claims_created_date'), table_name='wb_claims')
    op.drop_index(op.f('ix_wb_claims_claim_id'), table_name='wb_claims')
    op.drop_table('wb_claims')
    op.drop_index(op.f('ix_wb_cards_vendor_code'), table_name='wb_cards')
    op.drop_index(op.f('ix_wb_cards_nm_id'), table_name='wb_cards')
    op.drop_table('wb_cards')
    op.drop_index(op.f('ix_wb_campaigns_status'), table_name='wb_campaigns')
    op.drop_index(op.f('ix_wb_campaigns_advert_id'), table_name='wb_campaigns')
    op.drop_table('wb_campaigns')
    op.drop_index(op.f('ix_wb_campaign_stats_date'), table_name='wb_campaign_stats')
    op.drop_index(op.f('ix_wb_campaign_stats_advert_id'), table_name='wb_campaign_stats')
    op.drop_table('wb_campaign_stats')
    op.drop_index(op.f('ix_pickup_orders_order_uid'), table_name='pickup_orders')
    op.drop_index(op.f('ix_pickup_orders_order_id'), table_name='pickup_orders')
    op.drop_index(op.f('ix_pickup_orders_nm_id'), table_name='pickup_orders')
    op.drop_index(op.f('ix_pickup_orders_date'), table_name='pickup_orders')
    op.drop_table('pickup_orders')
    op.drop_index(op.f('ix_fbs_orders_order_uid'), table_name='fbs_orders')
    op.drop_index(op.f('ix_fbs_orders_order_id'), table_name='fbs_orders')
    op.drop_index(op.f('ix_fbs_orders_nm_id'), table_name='fbs_orders')
    op.drop_index(op.f('ix_fbs_orders_date'), table_name='fbs_orders')
    op.drop_table('fbs_orders')
    op.drop_index(op.f('ix_dbw_orders_order_uid'), table_name='dbw_orders')
    op.drop_index(op.f('ix_dbw_orders_order_id'), table_name='dbw_orders')
    op.drop_index(op.f('ix_dbw_orders_nm_id'), table_name='dbw_orders')
    op.drop_index(op.f('ix_dbw_orders_date'), table_name='dbw_orders')
    op.drop_table('dbw_orders')
    op.drop_index(op.f('ix_dbs_orders_order_uid'), table_name='dbs_orders')
    op.drop_index(op.f('ix_dbs_orders_order_id'), table_name='dbs_orders')
    op.drop_index(op.f('ix_dbs_orders_nm_id'), table_name='dbs_orders')
    op.drop_index(op.f('ix_dbs_orders_date'), table_name='dbs_orders')
    op.drop_table('dbs_orders')
    # ### end Alembic commands ###
