"""add_wb_seller_rating_and_subscriptions

Revision ID: cca7df82e106
Revises: a1b2c3d4e5f6
Create Date: 2026-04-03 13:09:26.408339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cca7df82e106'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
